name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run Ruff
        run: poetry run ruff check .
      - name: Run Mypy
        run: poetry run mypy src
      - name: Run Unit tests
        run: poetry run pytest -m "unit" --maxfail=1 --disable-warnings -q
      - name: Run Integration tests (if secrets exist)
        if: ${{ env.WORX_USER != '' && env.WORX_PASS != '' }}
        env:
          WORX_USER: ${{ secrets.WORX_USER }}
          WORX_PASS: ${{ secrets.WORX_PASS }}
          WORX_CLIENT_ID: ${{ secrets.WORX_CLIENT_ID }}
          WORX_CLIENT_SECRET: ${{ secrets.WORX_CLIENT_SECRET }}
        run: poetry run pytest -m "integration" --maxfail=1 --disable-warnings -q
